# Generated by Django 4.0.3 on 2022-04-17 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_followed_num_user_following_user_following_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followed_num',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following_num',
        ),
    ]
